{% set python_min = '3.11' %}
{% set name = "gufe" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OpenFreeEnergy/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 743481888ed14c5d51e9afd34d9c12d5ff2ee4f71d2ed85616112c3ec4ec1cfa 

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }},<3.14
    - setuptools
    - versioningit
  run:
    - msgpack-python
    - networkx
    - numpy 
    - openff-toolkit-base >=0.15.1
    - openff-units >=0.3.1
    - openmm <8.5  # unpin once 8.5 is checked
    - pint
    - pip
    - pooch >=1.9.0  # min needed for https://github.com/fatiando/pooch/issues/502
    - pydantic >=2.0,<2.12  # https://github.com/openforcefield/openff-interchange/issues/1346
    - python >={{ python_min }}
    - rdkit >=2024.09.1  # github.com/OpenFreeEnergy/gufe/issues/664
    - typing-extensions
    - zstandard

test:
  imports:
    - gufe
  requires:
    - pip
    - pooch
    - pytest
    - python {{ python_min }},<3.14 
  commands:
    - python -Ic "import gufe; print(gufe.__version__)"
    - pytest -v --pyargs gufe

about:
  home: https://github.com/OpenFreeEnergy/gufe
  summary: "gufe"
  description: |
    Abstract base classes for free energy calculations by Open Free Energy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://gufe.openfree.energy
  dev_url: https://github.com/OpenFreeEnergy/gufe

extra:
  recipe-maintainers:
    - IAlibay
    - dotsdl
    - dwhswenson
    - mikemhenry
    - atravitz
